import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import styles from './page.module.css';
import CustomLayout from '@/src/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Furniro',
  description: 'Generated by create next app and Kate',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <CustomLayout className={styles.layout}>{children}</CustomLayout>
        </AntdRegistry>
      </body>
    </html>
  )
}
